version: "3.8"
services:
    mongodb:
        image: mongo:4.4
        container_name: mongodb
        hostname: mongodb
        ports:
            - "8087:27017"
        command: [ "--bind_ip_all"]
        restart: "no"

    nestjs:
        image: node:16
        container_name: entry-task-fullstack-nest
        restart: "no"
        environment:
          - PORT=8080
          - HOST=0.0.0.0
          - MONGO_URI=mongodb://mongodb:27017
        ports:
          - 3000:8080
        volumes:
          - ./entry-task-fullstack-nest:/app
        depends_on:
          - mongodb
        command: bash -c "echo installing packages && npm install --prefix=/app && echo launching && npm run start:dev --prefix=/app"